### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by geopayme** [cryptocap/cryptocap-api#2]
besides this open forum, how does one contact you about account inquiries in the https://cryptocapital.co/ website... I would hardly thing someone can give personal financial details on a website without the ability first to login or even have a support email to contact someone!

If I use the wlox code do I need to use your https://cryptocapital.co/ site? much details is missing from the FAQ.

Thank you...

**Comment by ghost** [comment]
You can contact via their email on the cryptocapital.co site. You don't have to use cryptocapital to use WLOX.

contact@cryptocapital.co

**Comment by mbassan** [comment]
By the way, you can contact WLOX staff on Skype at support.wlox if you have any technical questions.
